[2025-07-18T04:20:34.950+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: batch_etl_pyspark.run_pyspark_etl manual__2025-07-18T04:15:22.090825+00:00 [queued]>
[2025-07-18T04:20:35.006+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: batch_etl_pyspark.run_pyspark_etl manual__2025-07-18T04:15:22.090825+00:00 [queued]>
[2025-07-18T04:20:35.008+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T04:20:35.010+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-07-18T04:20:35.014+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T04:20:35.124+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): run_pyspark_etl> on 2025-07-18 04:15:22.090825+00:00
[2025-07-18T04:20:35.173+0000] {standard_task_runner.py:55} INFO - Started process 337 to run task
[2025-07-18T04:20:35.193+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'batch_etl_pyspark', 'run_pyspark_etl', 'manual__2025-07-18T04:15:22.090825+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/batch_etl_dag.py', '--cfg-path', '/tmp/tmp50v27ncs']
[2025-07-18T04:20:35.220+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask run_pyspark_etl
[2025-07-18T04:20:35.902+0000] {task_command.py:388} INFO - Running <TaskInstance: batch_etl_pyspark.run_pyspark_etl manual__2025-07-18T04:15:22.090825+00:00 [running]> on host f5e43c0cbf33
[2025-07-18T04:20:36.514+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=batch_etl_pyspark
AIRFLOW_CTX_TASK_ID=run_pyspark_etl
AIRFLOW_CTX_EXECUTION_DATE=2025-07-18T04:15:22.090825+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-18T04:15:22.090825+00:00
[2025-07-18T04:20:36.521+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T04:20:36.532+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec spark spark-submit /opt/bitnami/spark/scripts/batch_etl_day.py']
[2025-07-18T04:20:36.584+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T04:20:36.760+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-07-18T04:20:36.772+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T04:20:36.832+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T04:20:36.852+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=batch_etl_pyspark, task_id=run_pyspark_etl, execution_date=20250718T041522, start_date=20250718T042034, end_date=20250718T042036
[2025-07-18T04:20:36.985+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task run_pyspark_etl (Bash command failed. The command returned a non-zero exit code 1.; 337)
[2025-07-18T04:20:37.060+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-07-18T04:20:37.164+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
